# Generated by Django 3.1 on 2020-08-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recruiter', models.CharField(max_length=150)),
                ('Client', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=100)),
                ('Recruiter_date', models.DateField(null=True)),
                ('Cv_sub_date', models.DateField(null=True)),
                ('Candidate_name', models.CharField(max_length=50)),
                ('Current_status_no', models.IntegerField(null=True)),
                ('Current_status_descr', models.CharField(max_length=30)),
                ('Interview_date', models.DateField(null=True)),
                ('Remarks', models.TextField()),
                ('Profile_skills', models.TextField()),
                ('Current_org', models.TextField()),
                ('Qualification', models.CharField(max_length=30)),
                ('Experience', models.IntegerField(null=True)),
                ('Current_loc', models.CharField(max_length=30)),
                ('Contact_no', models.IntegerField(null=True)),
                ('Alternate_contact_no', models.IntegerField(null=True)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Current_salary', models.IntegerField(null=True)),
                ('Expected_salary', models.IntegerField(null=True)),
                ('Notice_period', models.IntegerField(null=True)),
                ('Offer_date', models.DateField(null=True)),
                ('Offer_amount', models.IntegerField(null=True)),
                ('Joining_date', models.DateField(null=True)),
                ('Vacancy_code', models.IntegerField(null=True)),
                ('Applicant_code', models.IntegerField(null=True)),
                ('Birth_date', models.IntegerField(null=True)),
                ('Birth_month', models.IntegerField(null=True)),
                ('Birth_year', models.IntegerField(null=True)),
                ('Preferred_company', models.TextField()),
                ('Preferred_loc', models.TextField()),
                ('Week_no', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
            ],
        ),
    ]
