# Generated by Django 3.1 on 2020-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20200825_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Recruiter',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
