# Generated by Django 3.1 on 2020-08-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20200826_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Recruiter',
            field=models.CharField(max_length=150),
        ),
    ]
