# Generated by Django 3.1 on 2020-08-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20200826_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Recruiter',
            field=models.CharField(default='Individual', max_length=150),
        ),
    ]
