# Generated by Django 3.1 on 2020-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_auto_20200826_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Candidate_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
