# Generated by Django 3.1 on 2020-08-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_auto_20200826_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Client',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Current_Loc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Current_status_descr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Qualification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
