# Generated by Django 3.1 on 2020-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_auto_20200826_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Current_org',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Preferred_Loc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Preferred_company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Profile_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline_class',
            name='Remarks',
            field=models.TextField(null=True),
        ),
    ]
