# Generated by Django 3.1 on 2020-08-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_auto_20200826_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_class',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
