# Generated by Django 3.1 on 2020-08-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_auto_20200826_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline_class',
            name='Id',
        ),
    ]
